<a href="https://colab.research.google.com/github/raoaneesh24-pixel/Physics-Portfolio/blob/main/Gram_Schmidt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

#gram-schmidt process automated using numpy

In [ ]:

#manually input the vectors in U

def gram_schmidt(vectors):
    orthonormal_basis = []

    for v in vectors:                 #loops through every vector in U
        v = v.astype(float)

        for u in orthonormal_basis:
            v -= np.dot(v, u) * u     #projection

        v = v / np.linalg.norm(v)      #normalises vector

        orthonormal_basis.append(v)   #adds to list

    return np.array(orthonormal_basis)


U = np.array(
    [[1,2,3],
     [0,1,4],
     [5,6,0]]
)

print(f'Input:\n {U}')
print(f'Output: {gram_schmidt(U)}')


Input:
 [[1 2 3]
 [0 1 4]
 [5 6 0]]
Output: [[ 0.26726124  0.53452248  0.80178373]
 [-0.57735027 -0.57735027  0.57735027]
 [ 0.77151675 -0.6172134   0.15430335]]
